### ISSUE TITLE
Reduce specs boilerplate

### ISSUE THREAD

**Issue by acmcarther** [acmcarther/space_coop#40]
Specs services have a ton of boilerplate. There seems to be chatter from within specs to bake this into a macro, which would be nice. I can do that myself here as well.

**Comment by rschifflin** [comment]
theres definitely some low-hanging macro fruit in specs

**Comment by acmcarther** [comment]
I believe this has been solved or alleviated with my pubsub infra (#91) and explicit dep annotations (#101). Will create a more specific ticket if this is still a problem
